### ISSUE TITLE
Typescript declaration files breaks the code

### ISSUE THREAD

**Issue by Martinnord** [braintree/card-validator#85] opened 2020-08-18 15:57 UTC
### General information

- Library version: 8.0.0
- Browser and OS: Chrome: 84.0.4147.125 (Official Build) (64-bit) on MacOS 10.13.6

### Issue description

I installed the package via yarn for my React project written in TS. When I import the module like so,
```
import valid from "card-validator";
```
everything breaks with many type errors in the console:
![image](https://user-images.githubusercontent.com/17549362/90536030-d2146380-e17b-11ea-823f-40e2683274e5.png)

I thought I was on an outdated TS version, `3.5.3`, so I tried bumping it to the newest, `3.7.2`, but I got the same errors.

I also tried installing it on one of my JS projects and it worked fine.

**Comment by crookedneighbor** [comment] 2020-08-18 16:03
what does your tsconfig look like? You may need to use `esModuleInterop: true` in your compiler options since it's transpiled into commonjs.

**Comment by Martinnord** [comment] 2020-08-18 17:05
Sorry, forgot to past it. Here's my tsconfig:
```json
{
    "compilerOptions": {
        "sourceMap": true,
        "inlineSources": true,
        "sourceRoot": "/",
        "downlevelIteration": true,
        "target": "es6",
        "lib": ["es6", "dom", "esnext.asynciterable", "es2015", "es2017"],
        "allowJs": true,
        "skipLibCheck": true,
        "esModuleInterop": true,
        "allowSyntheticDefaultImports": true,
        "strict": true,
        "forceConsistentCasingInFileNames": true,
        "module": "esnext",
        "moduleResolution": "node",
        "rootDirs": ["src", "stories"],
        "resolveJsonModule": true,
        "isolatedModules": true,
        "strictNullChecks": true,
        "outDir": "./dist",
        "jsx": "react",
        "baseUrl": "./",
        "paths": {
            "Assets": ["src/assets/index.ts"],
            "TempUtils": ["src/admin/utils/index.js"],
            "Utils": ["src/utils/index.js"],
            "Providers": ["src/providers/index.js"],
            "Hooks": ["src/hooks/index.js"],
            "Components/*": ["src/Components/*"],
            "GraphQLQueries": ["src/graphql/queries/index.js"],
            "Constants": ["src/constants.ts"],
            "GraphQLMutations": ["src/graphql/mutations/index.js"],
            "Atoms": ["src/atoms/index.ts"],
            "Molecules": ["src/molecules/index.ts"],
            "Organisms": ["src/organisms/index.ts"],
            "Types": ["src/types/index.js"]
        }
    },
    "include": ["src/**/*"],
    "exclude": ["node_modules", "build", "scripts", "jest", "dist"]
}
```

**Comment by crookedneighbor** [comment] 2020-08-18 17:50
I'm not able to reproduce. Can you provide a sample repo that reproduces the problem?

**Comment by crookedneighbor** [comment] 2020-08-18 20:01
The only parts of your config I didn't use were the `paths` and `isolatedModules`

**Comment by Martinnord** [comment] 2020-08-18 20:50
Yes. Pushed my little project here, https://github.com/Martinnord/card-validator-reproduced.

It's made with create-react-app and I didn't touch the tsconfig. It's the default one.

**Comment by crookedneighbor** [comment] 2020-08-18 21:01
I was able to reproduce on your sample repo, but when I updated to typescript `3.9.7` I got no errors

**Comment by Martinnord** [comment] 2020-08-18 21:52
Okay. I don't know if I can just upgrade TS my bigger project like that. I mean, if something breaks. You don't know a workaround straight of the bat perhaps?

**Comment by crookedneighbor** [comment] 2020-08-18 23:41
The typescript package follows semver, so theoretically, it should only be new features and bug fixes, no breaking changes. 

I don't know enough about the inner workings of Typescript to know why it's erroring with 3.7, but since it works with the latest version, I'm going to close this.

If you know why it's erroring and want to open a PR to make it compatible with both 3.7 and the latest, for it.

**Closed by crookedneighbor** 2020-08-18 23:41 UTC
